logging:
    file:
        name: sboard.log
        path: /logs
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /
spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: jaeyoung0560@gmail.com
        password: cewwyjngexrkjgqr
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true
    application:
        name: sboard
        version: ${version}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://54.180.124.157:3306/board
        username: board
        password: Qwerty123@
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    thymeleaf:
        prefix: classpath:/templates